kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: easybuild-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
