kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: >-
      Jupyter notebook image with a set of data science libraries.
      A module extension allows to dynamically load libraries and applications.
    opendatahub.io/notebook-image-name: Standard Data Science - Modular
    opendatahub.io/notebook-image-url: 'https://github.com/thoth-station/s2i-generic-datascience-notebook'
  name: s2i-generic-datascience-lmod-notebook
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"Boto3","version":"1.17.11"},{"name":"Kafka-Python","version":"2.0.2"},{"name":"Matplotlib","version":"3.1.3"},{"name":"Numpy","version":"1.20.3"},{"name":"Pandas","version":"1.2.4"},{"name":"Scipy","version":"1.6.3"}]
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.9.7"}]'
      from:
        kind: DockerImage
        name: 'quay.io/guimou/s2i-generic-datascience-lmod-notebook:f34-py39_latest'
      referencePolicy:
        type: Source
