kind: Deployment
apiVersion: apps/v1
metadata:
  name: module-builder
  labels:
    app: module-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: module-builder
      app.kubernetes.io/part-of: module-builder
      deployment: module-builder
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: module-builder
        app.kubernetes.io/part-of: module-builder
        deployment: module-builder
    spec:
      initContainers:
        - resources:
            limits:
              cpu: '2'
              memory: 4096Mi
            requests:
              cpu: 500m
              memory: 500Mi
          name: easybuild-init
          imagePullPolicy: IfNotPresent
          image: 'quay.io/odh-highlander/module-builder:0.0.5'
          volumeMounts:
            - mountPath: /opt/apps/easybuild
              name: easybuild-data
          command:
            - /opt/app-root/src/easybuild_install.sh
      containers:
        - resources:
            limits:
              cpu: '8'
              memory: 8192Mi
            requests:
              cpu: 500m
              memory: 500Mi
          name: easybuild-run
          imagePullPolicy: IfNotPresent
          image: 'quay.io/odh-highlander/module-builder:0.0.5'
          volumeMounts:
            - mountPath: /opt/apps/easybuild
              name: easybuild-data
          command:
            - /opt/app-root/src/easybuild_run.sh
      volumes:
        - name: easybuild-data
          persistentVolumeClaim:
            claimName: easybuild-data
      terminationGracePeriodSeconds: 30
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
